// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivftoekivnehowrdtstn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2ZnRvZWtpdm5laG93cmR0c3RuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NDA1MTEsImV4cCI6MjA2MzIxNjUxMX0.zSbJBwoOwyVhkaAL_zl0t4n9me0qMV4JuThXSDqcPDs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);